version: '3.1'
services:
  web:
    image: odoo:13.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"

    volumes:
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    command: [ "odoo", "--test-enable", "--log-level=test" ]
  mydb:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
